Joshuadargan/redux sagas
edugator-cise/edugator-staff-frontend pull request #13
Opened 2021-09-16 00:31 UTC by joshuadargan

This PR does several things:
- Gets redux sagas added.
- Sets up the architecture for redux reducers, redux sagas, and jest tests
- Creates a demo action, reducer, and saga for the login page (not complete; will complete in another PR, these are primarily to show how to do redux sagas)
- Creates a test to test the reducer
- Adds an "npm run pre-pr" script to simplify pre-pr checks
- Creates a barebone "login" page to show how the state works and how to dispatch actions to the reducer and sagas.
![image](https://user-images.githubusercontent.com/40403340/133530403-ac5476f1-b0a9-4767-9e81-a0f252cb61a3.png)

#7 
#9

2021-09-16 14:07 UTC, marcgabe15 requested changes

2021-09-16 22:20 UTC, joshuadargan commented on src/app/common/appSettings.ts
> +  API_URL: "http://edugator-service-api.us-east-1.elasticbeanstalk.com",
Let's talk about it tomorrow

2021-09-17 16:20 UTC, marcgabe15 approved these changes
LGTM

2021-09-17 16:22 UTC, tanner-ropp approved these changes
LGTM 🤠

2021-09-17 16:27 UTC, merged